if [ -d "$HOME/.cargo/bin" ] ; then
  PATH="$HOME/.cargo/bin"
fi

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

export GOPATH="$HOME/Code/Go"

if [ -d "$HOME/Code/Go/bin" ] ; then
  PATH="$HOME/Code/Go/bin:$PATH"
fi
