if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

if [ -e /home/asoni/.nix-profile/etc/profile.d/nix.sh ]; then . /home/asoni/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

if [ -d "$HOME/.cargo/bin" ] ; then
    PATH="$HOME/.cargo/bin:$PATH"
fi

if [ -d "/snap/bin" ] ; then
  PATH="/snap/bin:$PATH"
fi
