export PATH="$HOME/.cargo/bin:$PATH"

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
export HOMEBREW_NO_INSTALL_CLEANUP=1
export HOMEBREW_NO_AUTO_UPDATE=1
export GOPATH="$HOME/Code/Go"

if [ -d "$HOME/Code/Go/bin" ] ; then
  PATH="$HOME/Code/Go/bin:$PATH"
fi
