export ZSH=$HOME/.dotfiles/zsh

# Setup fpath by looking for zsh files in all nested folders
for dir ($ZSH/*) if [ -d $dir ]; then fpath=($dir $fpath); fi;

export CLICOLOR=1

# Add colors to ls
alias ls="ls -GF"
alias ll="ls -GF -l"
alias la="ls -la -GF"

# History
HISTSIZE=10000
SAVEHIST=10000
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_find_no_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt hist_verify
setopt inc_append_history
setopt share_history

setopt autocd extendedglob nomatch notify
bindkey -e

autoload -Uz compinit
compinit
zstyle :compinstall filename '$HOME/.zshrc'
zstyle ':completion:*' menu yes select
# case insensitive match only when there are no case insensitive matches
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
# don't trigger completion if the pasted content has a tab
zstyle ':completion:*' insert-tab pending

autoload -Uz promptinit
promptinit
prompt pure

autoload -Uz select-word-style
select-word-style bash

# substring history
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search
bindkey "^[[B" down-line-or-beginning-search

# opam configuration
test -r /Users/asoni/.opam/opam-init/init.zsh && . /Users/asoni/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/asoni/.sdkman"
[[ -s "/Users/asoni/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/asoni/.sdkman/bin/sdkman-init.sh"
