ZSH_GIT_PROMPT_SHOW_STASH=1

source "$HOME/.zgen/zgen.zsh"

if ! zgen saved; then

  zgen oh-my-zsh

  zgen oh-my-zsh plugins/asdf

  zgen load mafredri/zsh-async
  zgen load sindresorhus/pure

  zgen load ael-code/zsh-colored-man-pages
  zgen load zdharma/fast-syntax-highlighting
  zgen load zdharma/history-search-multi-word
  zgen load zsh-users/zsh-autosuggestions
  zgen load supercrabtree/k
  zgen save
fi

# opam configuration
test -r /home/asoni/.opam/opam-init/init.zsh && . /home/asoni/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# Kitty
alias icat="kitty +kitten icat"
alias d="kitty +kitten diff"
alias gdiff="git difftool --no-symlinks --dir-diff"
kitty + complete setup zsh | source /dev/stdin

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
