source "$HOME/.zgen/zgen.zsh"

if ! zgen saved; then

  zgen oh-my-zsh

  zgen load mafredri/zsh-async
  zgen load sindresorhus/pure

  zgen load zdharma/zsh-diff-so-fancy
  zgen load ael-code/zsh-colored-man-pages
  zgen load zdharma/fast-syntax-highlighting
  zgen load zdharma/history-search-multi-word
  zgen load zsh-users/zsh-autosuggestions
  zgen load supercrabtree/k
  zgen save
fi

# opam configuration
test -r /home/asoni/.opam/opam-init/init.zsh && . /home/asoni/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash
